[package]
name = "foam_graph"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.11.0"
dotenv = "0.15.0"
jsonwebtoken = "9.3.1"
serde = {version = "1.0.219", features = ["derive"]}
sysinfo = "0.35.1"
tokio = "1.45.1"
actix-files = "0.6.6"